import React from 'react';import {createRoot}from'react-dom/client';import * as api from '@aikdna/kdna-react';import * as publicClient from '@aikdna/kdna-web-client';import{runMatrix}from'./matrix.mjs';import{makeDriver}from'./browser-driver.mjs';
window.runReactMatrix=base=>runMatrix(api,makeDriver,base,publicClient);
window.mountManualUI=async base=>{
 globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 let reader,serial=0;const counts={setup:0,cleanup:0};const mount=document.createElement('main');mount.id='manual-ui';document.body.append(mount);const root=createRoot(mount);
 function context(route,overrides={}){const s=reader.selection;const request={request_id:'request:ui:'+Date.now()+':'+(++serial),tuple:s.tuple,budget_bytes:1000000,mode:'exact_selection',selection:{asset_id:s.asset.asset_id,asset_version:s.asset.asset_version,judgment_id:'judgment:0'},handle:null,...overrides};return{association_id:'association:ui:'+Date.now()+':'+(++serial),endpoint_id:'endpoint:ui',session_id:'session:ui',endpoint_url:base+'/read/'+route,issued_at_ms:Date.now(),expires_at_ms:Date.now()+60000,outbound_request_json:JSON.stringify(request),correlation:{state:'validated',request_id:request.request_id},expected_tuple:s.tuple,expected_asset:s.asset,expected_digests:Object.fromEntries(['A','C','E'].map(k=>[k,s.digests[k].observed])),expected_snapshot_id:null,max_response_bytes:1000000,max_read_ms:5000,admission_response_limit_bytes:4096};}
 function App(){const [scenario,setScenario]=React.useState('received');const route={received:'valid',denied:'deny','no-body':'valid',failed:'failure',rejected:'json'}[scenario];reader=api.useKDNARead({endpointUrl:base+'/read/'+route,endpointId:'endpoint:ui',sessionId:'session:ui'});React.useEffect(()=>{counts.setup++;return()=>{counts.cleanup++;};},[]);return React.createElement(React.Fragment,null,
 React.createElement('h1',null,'Remote Read consumer'),React.createElement(api.KDNAFileInput,{onSelect:reader.select,disabled:reader.phase==='disposed'}),
 React.createElement('label',{htmlFor:'scenario'},'Response scenario'),React.createElement('select',{id:'scenario',value:scenario,onChange:e=>setScenario(e.target.value)},Object.keys({received:1,denied:1,'no-body':1,rejected:1,failed:1}).map(value=>React.createElement('option',{key:value,value},value))),
 React.createElement('div',{className:'actions'},React.createElement('button',{type:'button',disabled:!reader.selection,onClick:()=>reader.read(context(route,scenario==='no-body'?{budget_bytes:0}:{}))},'Read'),React.createElement('button',{type:'button',onClick:reader.cancel},'Cancel'),React.createElement('button',{type:'button',onClick:reader.release},'Release'),React.createElement('button',{type:'button',onClick:reader.dispose},'Dispose')),
 React.createElement(api.KDNAReadStatus,{state:reader}),React.createElement(api.KDNAReadView,{result:reader.result}));}
 await React.act(async()=>root.render(React.createElement(React.StrictMode,null,React.createElement(App))));
 globalThis.IS_REACT_ACT_ENVIRONMENT=false;
 window.manual={state:()=>({phase:reader.phase,code:reader.code,resultStatus:reader.result?.status,channel:reader.result?.view?.response.channel,selection:reader.selection?.fileName}),counts:()=>({...counts}),unmount:()=>{root.unmount();mount.remove();}};
};
