// Open-D's fresh React restart consumer cases; no acceptance-oracle imports.
export async function runMatrix(api, makeDriver, base, publicClient) {
 const rows=[];let serial=0;
 const eq=(actual,expected)=>{if(actual!==expected)throw Error(`expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);};
 const ok=(value,message='assertion failed')=>{if(!value)throw Error(message);};
 const bytes=new Uint8Array(await(await fetch(base+'/fixture.kdna')).arrayBuffer());
 const other=new Uint8Array(await(await fetch(base+'/other.kdna')).arrayBuffer());
 const encrypted=new Uint8Array(await(await fetch(base+'/encrypted.kdna')).arrayBuffer());
 function config(route='valid',extra={}){return {endpointUrl:base+'/read/'+route,endpointId:'endpoint:react-restart',sessionId:'session:react-restart',...extra};}
 function context(selection,route='valid',overrides={},extra={}) {
  const request={request_id:'request:react:'+Date.now()+':'+(++serial),tuple:selection.tuple,budget_bytes:1000000,mode:'exact_selection',selection:{asset_id:selection.asset.asset_id,asset_version:selection.asset.asset_version,judgment_id:'judgment:0'},handle:null,...overrides};
  return {association_id:'association:react:'+Date.now()+':'+(++serial),endpoint_id:'endpoint:react-restart',session_id:'session:react-restart',endpoint_url:config(route).endpointUrl,issued_at_ms:Date.now(),expires_at_ms:Date.now()+60000,outbound_request_json:JSON.stringify(request),correlation:{state:'validated',request_id:request.request_id},expected_tuple:selection.tuple,expected_asset:selection.asset,expected_digests:Object.fromEntries(['A','C','E'].map(k=>[k,selection.digests[k].observed])),expected_snapshot_id:null,max_response_bytes:1000000,max_read_ms:5000,admission_response_limit_bytes:4096,...extra};
 }
 async function test(name,fn){globalThis.__reactProgress={running:name,completed:rows.length};const start=performance.now();try{const detail=await fn();rows.push({name,pass:true,ms:performance.now()-start,detail:detail??null});}catch(e){rows.push({name,pass:false,ms:performance.now()-start,error:String(e),stack:e.stack});}}
 async function withDriver(route,extra,fn){const d=await makeDriver(config(route,extra));try{return await fn(d);}finally{await d.unmount();}}
 const chosen=async(d,input=bytes)=>{const s=await d.invoke('select',input);eq(s.status,'selected');return s.selection;};
 async function closedSelection(selection){const c=publicClient.createKDNAWebClient(config());try{eq((await c.read(selection,context(selection))).code,'CLIENT_SELECTION_INVALID');}finally{c.dispose();}}
 await test('four public runtime functions only',()=>{eq(Object.keys(api).sort().join(','),'KDNAFileInput,KDNAReadStatus,KDNAReadView,useKDNARead');});
 await test('read requires a selected public selection',()=>withDriver('valid',{},async d=>{eq((await d.invoke('read',{})).code,'REACT_SELECTION_REQUIRED');eq(d.state().phase,'failed');}));
 await test('selection is local and performs no fetch',()=>withDriver('valid',{fetch:()=>{throw Error('unexpected fetch');}},async d=>{await chosen(d);eq(d.state().phase,'selected');eq(d.state().result,null);}));
 await test('real Host HTTP produces received ViewModel in React',()=>withDriver('valid',{},async d=>{const s=await chosen(d);const p=d.start('read',context(s));eq(d.state().phase,'reading');const result=await d.finish(p);eq(result.status,'received');eq(d.state().result,result);eq(result.view.response.body.status,'ready');ok(d.html().includes('SAFE_TEXT'));ok(!d.html().includes('UNDISCLOSED_SECOND_RESULT'));return {status:result.status,channel:result.view.response.channel};}));
 await test('safe disclosed text is escaped and never creates markup',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('read',context(s));const html=d.html();ok(html.includes('&lt;img'));ok(html.includes('&lt;script'));ok(!html.includes('<img'));ok(!html.includes('<script'));ok(!html.includes('<a '));eq(globalThis.REACT_XSS,undefined);}));
 await test('denied remote envelope is received but projects denied',()=>withDriver('deny',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'deny'));eq(result.status,'received');eq(result.view.response.body.content,null);ok(d.html().includes('Read state: denied'));ok(d.html().includes('Content not disclosed.'));}));
 await test('admission rejection remains a denied remote response',()=>withDriver('valid',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'valid',{unknown:true}));eq(result.status,'received');eq(result.view.response.channel,'admission_rejection');ok(d.html().includes('Read state: denied'));}));
 await test('no-body control is explicitly rendered',()=>withDriver('valid',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'valid',{budget_bytes:0}));eq(result.view.response.channel,'no_body_control');eq(result.view.response.body,null);ok(d.html().includes('Read state: no-body'));}));
 await test('remote transport failure has no ready content',()=>withDriver('failure',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'failure'));eq(result.status,'received');eq(result.view.response.channel,'transport_failure');ok(d.html().includes('Read state: failed'));ok(!d.html().includes('SAFE_TEXT'));}));
 await test('invalid wire JSON remains public rejected result',()=>withDriver('json',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'json'));eq(result.status,'rejected');eq(result.view,null);ok(d.html().includes('Read state: rejected'));}));
 await test('caller endpoint mismatch fails without inferred context',()=>withDriver('valid',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'deny'));eq(result.code,'CLIENT_CONTEXT_MISMATCH');eq(d.state().phase,'failed');}));
 await test('two concurrent reads preserve each result and latest display',()=>withDriver('delay',{maxConcurrentRequests:2},async d=>{const s=await chosen(d),a=context(s,'delay'),b=context(s,'delay');const p=d.start('read',a),q=d.start('read',b);const [x,y]=await d.finish(Promise.all([p,q]));eq(x.status,'received');eq(y.status,'received');eq(d.state().result,y);eq(y.view.association.association_id,b.association_id);}));
 await test('public concurrency capacity is not bypassed',()=>withDriver('delay',{maxConcurrentRequests:1},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'delay'));const busy=await d.invoke('read',context(s,'delay'));eq(busy.code,'CLIENT_BUSY');eq((await d.finish(p)).status,'received');eq(d.state().result,busy);}));
 for(const mode of ['cancel','release','dispose']) await test('repeated same-stack '+mode+' uses actual React lifecycle',async()=>{for(let i=0;i<12;i++)await withDriver('delay',{},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'delay'));await d.invoke(mode);const result=await d.finish(p);eq(result.code,'CLIENT_CANCELLED');eq(d.state().phase,{cancel:'cancelled',release:'released',dispose:'disposed'}[mode]);eq(d.state().result,null);});return {iterations:12};});
 await test('external pre-abort stays a normal ClientResult',()=>withDriver('valid',{},async d=>{const s=await chosen(d),a=new AbortController();a.abort();eq((await d.invoke('read',context(s),{signal:a.signal})).code,'CLIENT_CANCELLED');}));
 await test('external same-stack abort stays a normal ClientResult',()=>withDriver('delay',{},async d=>{const s=await chosen(d),a=new AbortController();const p=d.start('read',context(s,'delay'),{signal:a.signal});a.abort();eq((await d.finish(p)).code,'CLIENT_CANCELLED');}));
 for(const mode of ['cancel','release','dispose'])await test('real in-flight '+mode+' aborts native fetch signal',async()=>{let ready,signal;const headers=new Promise(r=>{ready=r;});const fetcher=async(url,init)=>{signal=init.signal;const response=await fetch(url,init);ready();return response;};return withDriver('body-delay',{fetch:fetcher},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'body-delay'));await headers;await d.invoke(mode);eq((await d.finish(p)).code,'CLIENT_CANCELLED');eq(signal.aborted,true);return {signal_aborted:true};});});
 await test('actual timeout reaches React without content',()=>withDriver('body-delay',{timeoutMs:50},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s,'body-delay'));eq(result.code,'CLIENT_TIMEOUT');eq(d.state().phase,'failed');eq(d.state().result.view,null);}));
 await test('replacement aborts old read and releases previous selection',()=>withDriver('delay',{},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'delay'));const next=await chosen(d,other);eq((await d.finish(p)).code,'CLIENT_CANCELLED');eq(d.state().selection,next);eq(d.state().result,null);await closedSelection(s);}));
 await test('late ignored-abort fetch cannot publish after cancel',async()=>{let done,started;const completed=new Promise(r=>{done=r;}),sent=new Promise(r=>{started=r;});const fetcher=async(url,init)=>{started();const response=await fetch(url,{...init,signal:undefined});done();return response;};return withDriver('delay',{fetch:fetcher},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'delay'));await sent;await d.invoke('cancel');eq((await d.finish(p)).code,'CLIENT_CANCELLED');await d.finish(completed);eq(d.state().phase,'cancelled');eq(d.state().result,null);});});
 await test('late ignored-abort fetch cannot publish after unmount',async()=>{let done,started;const completed=new Promise(r=>{done=r;}),sent=new Promise(r=>{started=r;});const fetcher=async(url,init)=>{started();const response=await fetch(url,{...init,signal:undefined});done();return response;};const d=await makeDriver(config('delay',{fetch:fetcher}));const s=await chosen(d);const p=d.start('read',context(s,'delay'));await sent;await d.unmount();const renders=d.renders();await p;await completed;eq(d.renders(),renders);await closedSelection(s);});
 await test('late selection is released after replacement',()=>withDriver('valid',{},async d=>{const p=d.start('select',new Blob([bytes]));const q=d.start('select',other);const next=await d.finish(q);eq(next.status,'selected');eq((await d.finish(p)).code,'REACT_SELECTION_SUPERSEDED');eq(d.state().selection,next.selection);}));
 await test('selection completion after unmount cannot publish',async()=>{const d=await makeDriver(config());const p=d.start('select',new Blob([bytes]));await d.unmount();const renders=d.renders();eq((await p).code,'REACT_SELECTION_SUPERSEDED');eq(d.renders(),renders);});
 await test('cancel while selecting suppresses acquired selection',()=>withDriver('valid',{},async d=>{const p=d.start('select',new Blob([bytes]));d.start('cancel');eq((await d.finish(p)).code,'REACT_SELECTION_SUPERSEDED');eq(d.state().selection,null);eq(d.state().phase,'cancelled');}));
 await test('option replacement cleans old effect and creates a usable client',()=>withDriver('delay',{},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'delay'));await d.update(config());eq((await d.finish(p)).code,'CLIENT_CANCELLED');await closedSelection(s);eq(d.state().phase,'idle');const fresh=await chosen(d);eq((await d.invoke('read',context(fresh))).status,'received');}));
 await test('StrictMode committed effect remains usable after cleanup/setup',()=>withDriver('valid',{},async d=>{const s=await chosen(d);eq((await d.invoke('read',context(s))).status,'received');const counts=d.effects();ok(counts.setup>=1);if(d.kind==='browser'){ok(counts.setup>=2);ok(counts.cleanup>=1);}return counts;}));
 await test('exact maxFileBytes accepts',()=>withDriver('valid',{maxFileBytes:bytes.length},async d=>{await chosen(d);}));
 await test('maxFileBytes minus one rejects through public client',()=>withDriver('valid',{maxFileBytes:bytes.length-1},async d=>{eq((await d.invoke('select',bytes)).code,'CLIENT_FILE_TOO_LARGE');eq(d.state().phase,'rejected');}));
 await test('malformed bytes never become a selected file',()=>withDriver('valid',{},async d=>{eq((await d.invoke('select',new Uint8Array([1,2,3]))).status,'rejected');eq(d.state().selection,null);}));
 await test('encrypted unsupported file stays rejected',()=>withDriver('valid',{},async d=>{eq((await d.invoke('select',encrypted)).status,'rejected');eq(d.state().selection,null);}));
 await test('selection owns copied caller bytes',()=>withDriver('valid',{},async d=>{const input=bytes.slice();const s=await chosen(d,input);input.fill(0);eq((await d.invoke('read',context(s))).status,'received');}));
 await test('File name is public selection metadata only',()=>withDriver('valid',{},async d=>{const s=await chosen(d,new File([bytes],'<svg onload=alert(1)>.kdna'));eq(s.fileName,'<svg onload=alert(1)>.kdna');ok(!d.html().includes('<svg'));}));
 await test('release is idempotent and closes old selection',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('release');await d.invoke('release');eq(d.state().phase,'released');await closedSelection(s);}));
 await test('dispose is idempotent and denies further methods',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('dispose');await d.invoke('dispose');eq((await d.invoke('select',bytes)).code,'REACT_DISPOSED');eq((await d.invoke('read',context(s))).code,'REACT_DISPOSED');await closedSelection(s);}));
 await test('unmount releases the selected public resource',async()=>{const d=await makeDriver(config());const s=await chosen(d);await d.unmount();await closedSelection(s);});
 await test('invalid options fail in the UI effect without a fallback client',()=>withDriver('valid',{maxConcurrentRequests:0},async d=>{eq(d.state().code,'REACT_CLIENT_OPTIONS_INVALID');eq((await d.invoke('select',bytes)).code,'REACT_DISPOSED');}));
 await test('fresh received response never grants local capabilities',()=>withDriver('valid',{},async d=>{const s=await chosen(d);const result=await d.invoke('read',context(s));ok(Object.values(result.view.capabilities).every(x=>x===false));eq(result.view.proof_limits.remote_authorization,'NOT_PROVEN');ok(d.html().includes('no local authorization or action capability'));}));
 await test('positive expansion remains unsupported and undisclosed data absent',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('read',context(s));ok(d.html().includes('Cross-request expansion is unsupported (NOT_PROVEN)'));ok(!d.html().includes('UNDISCLOSED_SECOND_RESULT'));}));
 await test('rendered disclosed list is bounded with an explicit remainder',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('read',context(s,'valid',{mode:'catalog',selection:null}));await d.limits({maxVisibleNodes:1});ok(d.html().includes('1 additional disclosed items not displayed.'));}));
 await test('rendered text truncation is explicit',()=>withDriver('valid',{},async d=>{const s=await chosen(d);await d.invoke('read',context(s));await d.limits({maxTextCharacters:64});ok(d.html().includes('[display truncated]'));}));
 await test('invalid display limits fail closed',()=>{for(const options of [{maxVisibleNodes:0},{maxVisibleNodes:51},{maxTextCharacters:Infinity}]){let threw=false;try{api.KDNAReadView({result:null,...options});}catch(e){threw=e instanceof RangeError;}ok(threw);}});
 await test('transport association replay is not hidden or retried',()=>withDriver('valid',{},async d=>{const s=await chosen(d),c=context(s);eq((await d.invoke('read',c)).status,'received');const second=await d.invoke('read',c);eq(second.status,'rejected');eq(second.code,'READ_TRANSPORT_ASSOCIATION_REPLAYED');}));
 await test('cancelled selection can be read again with fresh context',async()=>{let ready;const headers=new Promise(r=>{ready=r;});const fetcher=async(url,init)=>{const response=await fetch(url,init);ready();return response;};return withDriver('body-delay',{fetch:fetcher},async d=>{const s=await chosen(d);const p=d.start('read',context(s,'body-delay'));await headers;await d.invoke('cancel');await d.finish(p);eq(d.state().selection,s);eq((await d.invoke('read',context(s,'body-delay'))).status,'received');});});
 await test('status has polite atomic native live semantics',()=>withDriver('valid',{},async d=>{const html=d.html();ok(html.includes('role="status"'));ok(html.includes('aria-live="polite"'));ok(html.includes('aria-atomic="true"'));ok(html.includes('type="file"'));ok(html.includes('<label'));}));
 return {total:rows.length,passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass).length,rows};
}
